site_name: Lead Service Line Map
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

theme:
  name: material
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  features:
    - navigation.tracking

repo_name: lead-service-line-map
repo_url: https://github.com/kedar-ketos/lead-service-line-map

nav:
  - Overview: index.md
  - Usage tutorial:
    - Objective: tutorial/objective.md
    - 1. Prerequisites: tutorial/prerequisites.md
    - 2. Get and transform data: tutorial/get_data.md
    - 3. Edit Power BI: tutorial/power_bi.md
    - 4. Publish: tutorial/publish.md
  - About the demo:
    - 1. Overview & features: demo/features.md
    - 2. Data sources: demo/data_sources.md
  - Contact us: contact.md